use serde::{Deserialize, Serialize};

use crate::simworld::types::{SimAction, SimOutcome, SimWorldEvent};

/// Every meaningful state-changing step is recorded as a typed event.
///
/// `RuntimeState` changes only through these events via the reducer —
/// no module mutates `RuntimeState` directly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", content = "payload")]
pub enum RuntimeEvent {
    /// A new observation arrived from a caller or SimWorld.
    ObservationReceived {
        input: String,
        source: String,
        cycle_id: u64,
    },

    /// A memory query was issued.
    MemoryQueried { query: String, cycle_id: u64 },

    /// A memory retrieval returned hits.
    MemoryHitReturned {
        cycle_id: u64,
        hit_count: usize,
        top_text: Option<String>,
    },

    /// A candidate was generated by a stream.
    CandidateGenerated {
        cycle_id: u64,
        candidate_id: String,
        stream: String,
        action_type: String,
        confidence: f64,
    },

    /// A candidate was rejected by the critic.
    CandidateRejected {
        cycle_id: u64,
        candidate_id: String,
        reason: String,
    },

    /// A candidate was selected as the winner.
    CandidateSelected {
        cycle_id: u64,
        candidate_id: String,
        action_type: String,
        selected_text: String,
    },

    /// A simworld action was applied to the world.
    ActionApplied {
        cycle_id: u64,
        action: SimAction,
        event: SimWorldEvent,
    },

    /// World state was updated after applying an action.
    WorldStateUpdated { cycle_id: u64, outcome: SimOutcome },

    /// An archive commit was performed.
    ArchiveCommitted {
        cycle_id: u64,
        frame_id: String,
        archive_path: String,
    },

    /// A contradiction was detected between two claims.
    ContradictionDetected {
        cycle_id: u64,
        claim_a: String,
        claim_b: String,
        subject: String,
    },

    /// A contradiction was resolved (old claim marked, not deleted).
    ContradictionResolved {
        cycle_id: u64,
        superseded_claim: String,
        active_claim: String,
        resolution: String,
    },

    /// The runtime mode changed (e.g. degradation).
    #[allow(dead_code)]
    RuntimeModeChanged {
        cycle_id: u64,
        from: String,
        to: String,
        reason: String,
    },
}

impl RuntimeEvent {
    /// The cycle ID carried by this event, if any.
    pub fn cycle_id(&self) -> Option<u64> {
        match self {
            Self::ObservationReceived { cycle_id, .. }
            | Self::MemoryQueried { cycle_id, .. }
            | Self::MemoryHitReturned { cycle_id, .. }
            | Self::CandidateGenerated { cycle_id, .. }
            | Self::CandidateRejected { cycle_id, .. }
            | Self::CandidateSelected { cycle_id, .. }
            | Self::ActionApplied { cycle_id, .. }
            | Self::WorldStateUpdated { cycle_id, .. }
            | Self::ArchiveCommitted { cycle_id, .. }
            | Self::ContradictionDetected { cycle_id, .. }
            | Self::ContradictionResolved { cycle_id, .. }
            | Self::RuntimeModeChanged { cycle_id, .. } => Some(*cycle_id),
        }
    }
}
